application: moonlit-shadow-813
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /test.*
  script: gaeunit.py

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /p/css
  static_dir: css

- url: /p/js
  static_dir: js

- url: /v/css
  static_dir: css

- url: /v/js
  static_dir: js

- url: /js/images
  static_dir: /js/images

- url: /server
  static_dir: server

- url: /fonts
  static_dir: fonts  

- url: /img
  static_dir: img

- url: /signup
  script: storefrontssar.app
  secure: always

- url: /login
  script: storefrontssar.app
  secure: always

- url: /forgot
  script: storefrontssar.app
  secure: always

- url: .*
  script: storefrontssar.app


libraries:
- name: webapp2
  version: latest
- name: PIL
  version: latest
- name: numpy
  version: latest
- name: pycrypto
  version: "2.6"
- name: django
  version: latest
